dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-1GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-1GB-MM.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-2GB-MM.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-2GB-HDMI.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-1GB-x28a.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-2GB-328.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-xjy.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-2GB-MM-328.dtb

dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-4GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-2GB-MM.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-4GB-MM.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-2GB-HDMI.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-4GB-HDMI.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-2GB-xa28a.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-4GB-xa28a.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-2GB-MM-xa28a.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-4GB-MM-xa28a.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-1GB-x28a.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
